In [283]:
# 2th order, two inputs
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv

inputs = [[1, 0],
         [1, 1],
         [0, 1],
         [0, 0]]
bias = 2
x0 =1
y_true = [1,0,1,0]

rowx = []

for i in inputs:
    rowx.append([x0,i[0],i[1],i[0]**2,i[0]*i[1],i[1]**2])


#u = sum(bias + )
random.uniform(-1,1)

rowW = np.random.uniform(-1,1,size=(1,6))
print(rowx)
print(rowW)

[[1, 1, 0, 1, 0, 0], [1, 1, 1, 1, 1, 1], [1, 0, 1, 0, 0, 1], [1, 0, 0, 0, 0, 0]]
[[ 0.94210544 -0.72839965 -0.7104931   0.38334947  0.60064626 -0.33664339]]


In [284]:

u = np.sum(np.dot(np.array(rowx), np.array(rowW).T), axis=1)
u

array([ 0.59705526,  0.15056503, -0.10503105,  0.94210544])

In [285]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [286]:
y_pred = sigmoid(u)
y_pred = np.array(y_pred)
y_pred

array([0.64498231, 0.53757031, 0.47376635, 0.71952475])

In [446]:

colW=np.array(weights).T
row_x=np.array(honu_inputs)
lr=2
colW = np.add(colW,lr*row_x.T*(y_true-y_pred)*row_x.T)
print(colW)
lr*row_x.T*(y_true-y_pred)

[[ 2.59778495  0.59941603  2.45109349  0.26245107]
 [ 2.08134317  0.08297425  0.08323066  0.08323066]
 [ 0.49142756  0.49117115  2.34284861  0.49142756]
 [ 1.57238458 -0.42598434 -0.42572793 -0.42572793]
 [ 0.23251268  0.23225627  0.23251268  0.23251268]
 [ 0.27679763  0.27654121  2.12821867  0.27679763]]


array([[ 1.99811251e+00, -2.56411610e-04,  1.85142105e+00,
        -3.37221368e-01],
       [ 1.99811251e+00, -2.56411610e-04,  0.00000000e+00,
        -0.00000000e+00],
       [ 0.00000000e+00, -2.56411610e-04,  1.85142105e+00,
        -0.00000000e+00],
       [ 1.99811251e+00, -2.56411610e-04,  0.00000000e+00,
        -0.00000000e+00],
       [ 0.00000000e+00, -2.56411610e-04,  0.00000000e+00,
        -0.00000000e+00],
       [ 0.00000000e+00, -2.56411610e-04,  1.85142105e+00,
        -0.00000000e+00]])

In [447]:
u = np.sum(np.dot(np.array(rowx), np.array(colW)), axis=1)
u

array([ 8.53646865, 16.24149299, 12.68597557,  5.91074555])

In [448]:
y_pred = sigmoid(u)
y_pred = np.array(y_pred)
y_pred

array([0.99980386, 0.99999991, 0.99999691, 0.99729716])

In [127]:
m = np.arange(1,10).reshape(3,3)

In [130]:
print(m.flatten())

[1 2 3 4 5 6 7 8 9]


In [131]:
x = [1,2,3]

In [133]:
np.dot(x,m.T)

array([14, 32, 50])

In [159]:
m = np.arange(1,17).reshape(4,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [188]:
col_w = []
row_n = 0
for i in m:
    for j in i[row_n:]:
        col_w.append(j)
    row_n+=1
col_w

[1, 2, 3, 4, 6, 7, 8, 11, 12, 16]

In [189]:
inputs = [1,2,3]
bias = 4
row_x = [bias,
       inputs[0], inputs[1], inputs[2],
       inputs[0]*inputs[0], inputs[0]*inputs[1], inputs[0]*inputs[2], 
       inputs[1]*inputs[1], inputs[1]*inputs[2], 
       inputs[2]*inputs[2]]


In [195]:
u = np.dot(row_x, np.array(col_w).T)
y = sigmoid(u)
y

1.0

In [470]:
np.subtract(np.eye(6,6),lr*np.array(row_x[0]).T*row_x[0])*colW.T[0]

array([[-2.59778495, -4.16268633,  0.        , -3.14476916,  0.        ,
         0.        ],
       [-5.1955699 , -2.08134317,  0.        , -3.14476916,  0.        ,
         0.        ],
       [-5.1955699 , -4.16268633,  0.49142756, -3.14476916,  0.        ,
         0.        ],
       [-5.1955699 , -4.16268633,  0.        , -1.57238458,  0.        ,
         0.        ],
       [-5.1955699 , -4.16268633,  0.        , -3.14476916,  0.23251268,
         0.        ],
       [-5.1955699 , -4.16268633,  0.        , -3.14476916,  0.        ,
         0.27679763]])

array([2.59778495, 0.59941603, 2.45109349, 0.26245107])